baseURL: "https://kqding.github.io" 
title: Keqin 'Catherine' Ding
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        
        - name: Projects # NOTE - this is what shows up on the top right side
          url: projects/
          weight: 2
        - name: Publications
          url: publications/
          weight: 3
        - name: News
          url: news/
          weight: 4 
        # - name: Books
        #   url: books/
        #   weight: 5 


params:
    description: "I am a PhD candidate in Biomedical Engineering at Johns Hopkins University. I specialize in sensory neural prostheses and neural signal processing. I develop computational methods to understand how the brain adapts to artificial sensory inputs and quantify the spatial reliability of neural stimulation percept maps for functional use. 
            My work has applications in brain-computer interfaces, human-machine interaction, and neuromodulation."
    author: Catherine Ding
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # MainSections: ["research","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Keqin 'Catherine' Ding
          subtitle: "
            I am a PhD candidate in Biomedical Engineering at Johns Hopkins University, advised by Dr. [<u>Nitish Thakor</u>](https://www.bme.jhu.edu/people/faculty/nitish-v-thakor/) (<em>expected graduation: 12/2025</em>). 
            I develop **computational frameworks for neural interfaces** that combine neural signal analysis, computational modeling, and network-based methods to study sensory neural prostheses.
            <br><br>
            My research focuses on two key areas that address critical challenges in neural interface development: 1) characterizing how the brain adapts to artificial sensory inputs, and 2) quantifying the spatial reliability of neural stimulation percept maps.
            <br><br>
            My work combines experimental and computational approaches that inform advances in brain-computer interfaces, neuromodulation, human-machine interaction, and human-centered technologies.
            "
          imageUrl: "Ding_Profile.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Publications
              url: publications/
            - name: News
              url: news/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
              # url: 

    socialIcons:
        # - name: CV
        #   url: Ding_CV.pdf
        # - name: Email
          # url: mailto:
        # - name: Location
        #   url: location/
        - name: LinkedIn
          url: https://www.linkedin.com/in/ckqding
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=RgfF6SAAAAAJ&hl=en
        # - name: GitHub
        #   url: 
        # - name: Bluesky
        #   url: 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Catherine Ding"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2