baseURL: "https://kqding.github.io" 
title: Keqin 'Catherine' Ding
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        
        - name: Research # NOTE - this is what shows up on the top right side
          url: research/
          weight: 2
        - name: Publications
          url: publications/
          weight: 3
        - name: News
          url: news/
          weight: 4 
        # - name: Books
        #   url: books/
        #   weight: 5 


params:
    description: "I am a PhD candidate in Biomedical Engineering at Johns Hopkins University. My research focuses on studying the integration of artificial tactile sensations for advancing neural prostheses and human-machine interfaces."
    author: Catherine Ding
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # MainSections: ["research","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Keqin 'Catherine' Ding
          subtitle: "I am currently a PhD candidate in Biomedical Engineering supervised by Dr. [<u>Nitish Thakor</u>](https://www.bme.jhu.edu/people/faculty/nitish-v-thakor/) at the Johns Hopkins University (<em>expected graduation: 12/2025</em>). 
            <br><br>
            
            My research focuses on studying the **integration of artificial tactile sensations** for advancing neural prostheses and human-machine interfaces. 
            My thesis involves developing computational techniques to investigate the spatial stability of sensory stimulation, and using network methods to understand cortical responses to sensory stimulation.
            "
          imageUrl: "Ding_Profile.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Publications
              url: publications/
            - name: News
              url: news/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
              # url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        # - name: CV
        #   url: Ding_CV.pdf
        # - name: Email
          # url: mailto:moritz.maria.von.igelfeld@gmail.com
        # - name: Location
        #   url: location/
        - name: LinkedIn
          url: https://www.linkedin.com/in/ckqding
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=RgfF6SAAAAAJ&hl=en
        # - name: GitHub
        #   url: https://github.com/KQDing
        # - name: Bluesky
        #   url: https://bsky.app/profile/ckqding.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Catherine Ding"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2